name: sina_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.2
  drift: ^2.34.1
  drift_flutter: ^0.3.1
  path_provider: ^2.1.6
  uuid: ^4.5.3
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.34.0
  build_runner: ^2.15.1
  test: ^1.31.0

flutter:
  uses-material-design: true
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/space_grotesk.ttf
    - family: InstrumentSans
      fonts:
        - asset: assets/fonts/instrument_sans.ttf
